### PR TITLE
Updated formula for Souffle 2.3 and MacOS 13.0

### PR DESCRIPTION
**Pull request by kpadmasola**
+ Resolves https://github.com/souffle-lang/homebrew-souffle/issues/12
+ thanks to https://github.com/luc-tielen for helping with this fix

### CODE REVIEW

**Comment by kpadmasola** [comment]
Sample output from `brew reinstall -d -v --build-from-source ./souffle.rb`
```
==> Cloning https://github.com/souffle-lang/souffle
git config remote.origin.url https://github.com/souffle-lang/souffle
Updating /Users/padmasol/Library/Caches/Homebrew/souffle--git
git config remote.origin.fetch \+refs/tags/2.3:refs/tags/2.3
git config remote.origin.tagOpt --no-tags
git config advice.detachedHead false
git --git-dir /Users/padmasol/Library/Caches/Homebrew/souffle--git/.git rev-parse -q --verify 2.3\^\{commit\}
git checkout -f 2.3 --
==> Checking out tag 2.3
HEAD is now at cc8ea0917 Merge pull request #2272 from b-scholz/changelog2.3
git reset --hard 2.3 --
HEAD is now at cc8ea0917 Merge pull request #2272 from b-scholz/changelog2.3
==> Reinstalling souffle
...
==> cmake -B build -S . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/souffle/2.3 -DSOUFFLE_BASH_COMPLETION=OFF -DCMAKE_CXX_COMPILER=g++-11
...
==> cmake --build build --target install -j
...
[100%] Built target souffle
Install the project...
-- Install configuration: "Release"
...
==> Cleaning
...
==> Finishing up
...
==> Summary
🍺  /usr/local/Cellar/souffle/2.3: 99 files, 11.4MB, built in 2 minutes 45 seconds
```

**Comment by kpadmasola** [comment]
Sample output from `brew test ./souffle.rb`
```
==> Testing souffle
==> /usr/local/Cellar/souffle/2.3/bin/souffle --version 2>&1
```

**Comment by kpadmasola** [comment]
@b-scholz Can you please review and merge if this looks ok? Thanks!

**Review by b-scholz — APPROVED** [review]
Thanks for fixing it!

**Pull request merged**
